//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pendu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pendu.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez saisir une lettre..
        /// </summary>
        internal static string DemandeLettre {
            get {
                return ResourceManager.GetString("DemandeLettre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonjour et bienvenue !
        ///Quel est votre prénom ?.
        /// </summary>
        internal static string DemandePrenom {
            get {
                return ResourceManager.GetString("DemandePrenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous rejouer?.
        /// </summary>
        internal static string DemandeRejouer {
            get {
                return ResourceManager.GetString("DemandeRejouer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facile.
        /// </summary>
        internal static string Diff1 {
            get {
                return ResourceManager.GetString("Diff1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Facile &lt;15 points de vie&gt;.
        /// </summary>
        internal static string Diff1Desc {
            get {
                return ResourceManager.GetString("Diff1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal.
        /// </summary>
        internal static string Diff2 {
            get {
                return ResourceManager.GetString("Diff2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Normal &lt;10 points de vie&gt;.
        /// </summary>
        internal static string Diff2Desc {
            get {
                return ResourceManager.GetString("Diff2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to difficile.
        /// </summary>
        internal static string Diff3 {
            get {
                return ResourceManager.GetString("Diff3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - Difficile &lt;5 points de vie&gt;.
        /// </summary>
        internal static string Diff3Desc {
            get {
                return ResourceManager.GetString("Diff3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enchanté {0}, veuillez choisir votre niveau de difficulté..
        /// </summary>
        internal static string DiffChoix {
            get {
                return ResourceManager.GetString("DiffChoix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parfait {0}, je jeu va démarrer en mode {1}..
        /// </summary>
        internal static string DispDifficulte {
            get {
                return ResourceManager.GetString("DispDifficulte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meilleur score à battre: {0}.
        /// </summary>
        internal static string DispMeilleurScore {
            get {
                return ResourceManager.GetString("DispMeilleurScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voici le mot à deviner: {0}.
        /// </summary>
        internal static string DispMot {
            get {
                return ResourceManager.GetString("DispMot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - English / Anglais.
        /// </summary>
        internal static string En {
            get {
                return ResourceManager.GetString("En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Veuillez saisir un nombre valide..
        /// </summary>
        internal static string ErreurNombre {
            get {
                return ResourceManager.GetString("ErreurNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dommage {0}, vous êtes mort. Le mot était {1}..
        /// </summary>
        internal static string FinFalse {
            get {
                return ResourceManager.GetString("FinFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bravo {0}, vous avez réussi, le mot était bien {1}!
        ///Votre score est de {2} point{3}!.
        /// </summary>
        internal static string FinTrue {
            get {
                return ResourceManager.GetString("FinTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Français / French.
        /// </summary>
        internal static string Fr {
            get {
                return ResourceManager.GetString("Fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parlez-vous français ou anglais?
        ///Do you speak english or french?.
        /// </summary>
        internal static string Langue {
            get {
                return ResourceManager.GetString("Langue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La lettre {0} n&apos;existe pas dans le mot. Il vous reste {1} point{2} de vie..
        /// </summary>
        internal static string LettreFalse {
            get {
                return ResourceManager.GetString("LettreFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La lettre est déjà jouée..
        /// </summary>
        internal static string LettreJouee {
            get {
                return ResourceManager.GetString("LettreJouee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bravo, la lettre {0} est la {1}° lettre du mot!.
        /// </summary>
        internal static string LettreTrue {
            get {
                return ResourceManager.GetString("LettreTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE JEU DU PENDU
        ///Meilleur Score: {0}.
        /// </summary>
        internal static string MessageBienvenue {
            get {
                return ResourceManager.GetString("MessageBienvenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeaaaah! Vous avez battu le meilleur score! (ancien: {0}).
        /// </summary>
        internal static string NouveauMeilleurScore {
            get {
                return ResourceManager.GetString("NouveauMeilleurScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Oui.
        /// </summary>
        internal static string Rejouer1 {
            get {
                return ResourceManager.GetString("Rejouer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Non.
        /// </summary>
        internal static string Rejouer2 {
            get {
                return ResourceManager.GetString("Rejouer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE PENDU.
        /// </summary>
        internal static string TitreConsole {
            get {
                return ResourceManager.GetString("TitreConsole", resourceCulture);
            }
        }
    }
}
